name: Workflow1

on: 
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    permissions: 
      contents: write
      
    steps:
      - name: STEP 1 Clonar Repo
        uses: actions/checkout@v7
        
      - name: STEP 2 Setup de Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
          
      - name: STEP 2.5 Correr script
        run: python ./Actions/Examples/script.py

      - name: STEP 3 Commit y push de los cambios
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Autocommit desde action
          commit_user_name: Git Actions
          commit_user_email: edwinsotohz@gmail.com 
          commit_author: EdwinSotoSHz <edwinsotohz@gmail.com>
        
